/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedatabase;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;


/**
 *
 * @author Vlachogiannis
 */
public class MovieSearch extends javax.swing.JFrame {

    private EntityManager em; // Ο EntityManager
    private EntityManagerFactory emf;
    
    /**
     * Creates new form MovieSearch
     */
    public MovieSearch() {
        initComponents();
        initializeComboBox();
    }
    
    public void initializeComboBox(){
        try {
            ComboBox.insertItemAt("--Επέλεξε Τύπο--", 0);
            ComboBox.setSelectedIndex(0);
            emf = Persistence.createEntityManagerFactory("MovieDatabasePU");
            em=emf.createEntityManager();
            // Καλούμε query απο βάση για να φέρουμε τον πίνακα Genre
            TypedQuery<Genre> q1 = em.createNamedQuery("Genre.findAll", Genre.class);
            // Εγγραφή όλων των ειδών μέσα στο JComboBox
            for (int i=0; i<q1.getResultList().size(); i++)
                //Περιορισμός στους επιθυμητούς τύπους ταινιών
                if (q1.getResultList().get(i).getId()==28 || q1.getResultList().get(i).getId()==10749 
                    || q1.getResultList().get(i).getId()==878){
                    ComboBox.addItem(q1.getResultList().get(i).getName());
                }
        }
        catch(Exception ex){
            System.err.println(ex);
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MovieDatabasePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("MovieDatabasePU").createEntityManager();
        genreQuery = java.beans.Beans.isDesignTime() ? null : MovieDatabasePUEntityManager.createQuery("SELECT g FROM Genre g");
        genreList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : genreQuery.getResultList();
        genreQuery1 = java.beans.Beans.isDesignTime() ? null : MovieDatabasePUEntityManager.createQuery("SELECT g FROM Genre g");
        genreList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : genreQuery1.getResultList();
        genreQuery2 = java.beans.Beans.isDesignTime() ? null : MovieDatabasePUEntityManager.createQuery("SELECT g FROM Genre g");
        genreList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : genreQuery2.getResultList();
        ParentPanel = new javax.swing.JPanel();
        ComboBox = new javax.swing.JComboBox<>();
        ClearButton = new javax.swing.JButton();
        outYear = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Αναζήτηση Ταινιών");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        ParentPanel.setBackground(new java.awt.Color(102, 102, 102));
        ParentPanel.setForeground(new java.awt.Color(204, 204, 204));

        ComboBox.setBackground(new java.awt.Color(204, 204, 204));
        ComboBox.setForeground(new java.awt.Color(0, 0, 0));
        ComboBox.setToolTipText("");
        ComboBox.setName(""); // NOI18N

        ClearButton.setBackground(new java.awt.Color(204, 204, 204));
        ClearButton.setForeground(new java.awt.Color(0, 0, 0));
        ClearButton.setText("Καθαρισμός");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        outYear.setBackground(new java.awt.Color(204, 204, 204));
        outYear.setForeground(new java.awt.Color(0, 0, 0));
        outYear.setText("Έτος Κυκλοφορίας");
        outYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outYearMouseClicked(evt);
            }
        });
        outYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                outYearKeyPressed(evt);
            }
        });

        findButton.setBackground(new java.awt.Color(204, 204, 204));
        findButton.setForeground(new java.awt.Color(0, 0, 0));
        findButton.setText("Αναζήτηση");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        ReturnButton.setBackground(new java.awt.Color(153, 0, 51));
        ReturnButton.setForeground(new java.awt.Color(0, 0, 0));
        ReturnButton.setText("Επιστροφή");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        ErrorLabel.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout ParentPanelLayout = new javax.swing.GroupLayout(ParentPanel);
        ParentPanel.setLayout(ParentPanelLayout);
        ParentPanelLayout.setHorizontalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParentPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ParentPanelLayout.createSequentialGroup()
                        .addGroup(ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outYear, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(ClearButton)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParentPanelLayout.createSequentialGroup()
                        .addComponent(ReturnButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParentPanelLayout.createSequentialGroup()
                        .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        ParentPanelLayout.setVerticalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ParentPanelLayout.createSequentialGroup()
                        .addComponent(ComboBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outYear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        outYear.setText("");
        ErrorLabel.setText("");
        ComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void outYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outYearMouseClicked
        outYear.setText("");
    }//GEN-LAST:event_outYearMouseClicked

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        //Επιλέγω το Eίδος Ταινίας και Εισάγω το Έτος
        String comboSelect = String.valueOf(ComboBox.getSelectedItem());
        String year = outYear.getText();
        resultsToTable search = new resultsToTable();
        search.setVisible(false);
    }//GEN-LAST:event_findButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        ParentPanel.setEnabled(true);
        dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void outYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outYearKeyPressed
        
        char text = evt.getKeyChar();
        //Αποτροπή χρήστη απο την χρησιμοποίηση χαρακρήρων στο jTextField
        if (Character.isLetter(text)){
            outYear.setEditable(false);
            ErrorLabel.setText("Επιτρέπονται μόνο χρονολογίες απο 2000-2019!");
        }
        else{
            outYear.setEditable(true);
        }  
    }//GEN-LAST:event_outYearKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JLabel ErrorLabel;
    private javax.persistence.EntityManager MovieDatabasePUEntityManager;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton findButton;
    private java.util.List<moviedatabase.Genre> genreList;
    private java.util.List<moviedatabase.Genre> genreList1;
    private java.util.List<moviedatabase.Genre> genreList2;
    private javax.persistence.Query genreQuery;
    private javax.persistence.Query genreQuery1;
    private javax.persistence.Query genreQuery2;
    private javax.swing.JTextField outYear;
    // End of variables declaration//GEN-END:variables
}
