/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedatabase;

import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;

/**
 *
 * @author Morenita
 */
public class resultsToTable extends javax.swing.JFrame {

    private EntityManager em; // Ο EntityManager
    private EntityManagerFactory emf;
    /**
     * Creates new form resultsToTable
     */
    public resultsToTable() {
        initComponents();
        favListComboBox();
        searchTable();
    }

    public void favListComboBox(){
        try {
            favListCombo.insertItemAt("--Προσθήκη σε Λίστα--", 0);
            favListCombo.setSelectedIndex(0);
            emf = Persistence.createEntityManagerFactory("MovieDatabasePU");
            em=emf.createEntityManager();
            // Καλούμε query απο βάση για να φέρουμε τον πίνακα Genre
            TypedQuery<FavoriteList> favList1 = em.createNamedQuery("FavoriteList.findAll", FavoriteList.class);
            // Εγγραφή όλων των λιστών μέσα στο JComboBox
            for (int i=0; i<favList1.getResultList().size(); i++)
                favListCombo.addItem(favList1.getResultList().get(i).getName());
                
        }
        catch(Exception ex){
            System.err.println(ex);
            System.exit(1);
        }
    }

    public void searchTable(){
        
        ArrayList<Movie> movies = new ArrayList<>();
        
        try {
            emf = Persistence.createEntityManagerFactory("MovieDatabasePU");
            em=emf.createEntityManager();
            // Καλούμε query απο βάση για να φέρουμε τον πίνακα Movie
            TypedQuery<Movie> q2 = em.createNamedQuery("Movie.findAll", Movie.class);
            for (int i=0; i<q2.getResultList().size(); i++){
            movies.add(q2.getResultList().get(i));
            }
        }
        catch(Exception ex){
            System.err.println(ex);
            System.exit(1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        favListCombo = new javax.swing.JComboBox<>();
        errorLabel = new javax.swing.JLabel();
        ReturnButton = new javax.swing.JButton();
        removeFromList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        resultsPanel.setBackground(new java.awt.Color(102, 102, 102));
        resultsPanel.setForeground(new java.awt.Color(0, 0, 0));

        resultsTable.setBackground(new java.awt.Color(102, 102, 102));
        resultsTable.setBorder(new javax.swing.border.MatteBorder(null));
        resultsTable.setForeground(new java.awt.Color(0, 0, 0));
        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Τίτλος Ταινίας", "Βαθμολογία", "Περιγραφή"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resultsTable.getTableHeader().setReorderingAllowed(false);
        resultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultsTable);

        favListCombo.setBackground(new java.awt.Color(102, 102, 102));
        favListCombo.setForeground(new java.awt.Color(0, 0, 0));

        ReturnButton.setBackground(new java.awt.Color(153, 0, 51));
        ReturnButton.setForeground(new java.awt.Color(0, 0, 0));
        ReturnButton.setText("Ακύρωση");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        removeFromList.setBackground(new java.awt.Color(153, 0, 51));
        removeFromList.setForeground(new java.awt.Color(0, 0, 0));
        removeFromList.setText("Remove From List");

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addComponent(favListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeFromList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ReturnButton)))
                .addContainerGap())
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeFromList, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(errorLabel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resultsTableMouseClicked

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        resultsPanel.setEnabled(true);
        dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JComboBox<String> favListCombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeFromList;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JTable resultsTable;
    // End of variables declaration//GEN-END:variables
}
